server:
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
securityconfig:
  logoutsuccssurl: /
  permitall: /rest/**,/bbs**
  deniedpage: /deny
  urlroles: /**/new/** = admin; /**/edit/** = admin,editor; /**/delete/** = admin